# Generated by Django 3.0.6 on 2020-06-02 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CareSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cs_index', models.CharField(max_length=50)),
                ('cs_name', models.CharField(max_length=50)),
                ('cs_desc', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['cs_index'],
            },
        ),
        migrations.CreateModel(
            name='IssueLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('il_index', models.CharField(max_length=50)),
                ('il_name', models.CharField(max_length=50)),
                ('il_desc', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['il_index'],
            },
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sy_index', models.CharField(max_length=50)),
                ('sy_name', models.CharField(max_length=50)),
                ('sy_desc', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['sy_index'],
            },
        ),
        migrations.CreateModel(
            name='SystemFunction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sf_index', models.CharField(max_length=50)),
                ('sf_name', models.CharField(max_length=50)),
                ('sf_parent', models.CharField(max_length=50)),
                ('sf_desc', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['sf_index'],
            },
        ),
    ]
