# Generated by Django 3.0.6 on 2020-06-04 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart_main', '0002_auto_20200602_2344'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='System',
            new_name='SystemModel',
        ),
    ]
