# Generated by Django 3.0.6 on 2020-06-06 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart_main', '0003_auto_20200604_1659'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemmodel',
            options={'ordering': ['sy_name']},
        ),
        migrations.RemoveField(
            model_name='systemmodel',
            name='sy_index',
        ),
    ]
