# Generated by Django 3.0.6 on 2020-06-07 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_main', '0004_auto_20200606_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemfunction',
            name='sf_parent',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
