# Generated by Django 3.0.6 on 2020-06-09 19:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('smart_main', '0005_auto_20200607_2028'),
    ]

    operations = [
        migrations.CreateModel(
            name='HazardInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hi_name', models.CharField(max_length=50)),
                ('hi_desc', models.TextField(blank=True)),
                ('hi_inse', models.PositiveIntegerField(default=0)),
                ('hi_inli', models.PositiveIntegerField(default=0)),
                ('hi_rese', models.PositiveIntegerField(default=0)),
                ('hi_reli', models.PositiveIntegerField(default=0)),
                ('hi_inrr', models.PositiveIntegerField(default=0)),
                ('hi_rerr', models.PositiveIntegerField(default=0)),
                ('hi_clju', models.TextField(blank=True)),
                ('hi_parent', models.CharField(blank=True, max_length=50)),
                ('hi_ps', models.CharField(blank=True, max_length=50)),
                ('hi_sf', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['hi_name'],
            },
        ),
        migrations.CreateModel(
            name='HazardType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ht_name', models.CharField(max_length=50)),
                ('ht_desc', models.TextField(blank=True)),
            ],
        ),
    ]
