# Generated by Django 3.0.6 on 2020-06-18 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart_main', '0007_auto_20200613_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hazardinstance',
            name='hi_sf_name',
        ),
    ]
