# Generated by Django 3.0.6 on 2020-06-18 18:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('smart_main', '0008_remove_hazardinstance_hi_sf_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessEdge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=50)),
                ('target', models.CharField(max_length=50)),
                ('pe_ps', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=50)),
                ('pn_desc', models.TextField(blank=True)),
                ('x', models.CharField(max_length=50)),
                ('y', models.CharField(max_length=50)),
                ('pn_cs', models.CharField(blank=True, max_length=50)),
                ('pn_ps', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessSystem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ps_name', models.CharField(max_length=50)),
                ('ps_desc', models.TextField(blank=True)),
            ],
        ),
    ]
