# Generated by Django 3.0.6 on 2020-06-21 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_main', '0010_auto_20200618_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processnode',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
