# Generated by Django 3.0.6 on 2020-06-22 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_main', '0012_auto_20200621_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processedge',
            name='label',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
