# Generated by Django 3.0.6 on 2020-06-23 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_main', '0014_processedge_pe_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processedge',
            name='target',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
