# Generated by Django 3.0.6 on 2020-06-23 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_main', '0016_auto_20200623_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processnode',
            name='label',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
