# Generated by Django 3.0.6 on 2020-06-25 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_main', '0017_auto_20200623_1909'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessNode_HazardInstance',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('pn', models.CharField(max_length=50)),
                ('hi', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessNode_SystemFunction',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('pn', models.CharField(max_length=50)),
                ('sf', models.CharField(max_length=50)),
            ],
        ),
    ]
