# Generated by Django 3.0.6 on 2020-06-27 16:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('smart_main', '0018_processnode_hazardinstance_processnode_systemfunction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processnode_hazardinstance',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='processnode_systemfunction',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
