# Generated by Django 3.0.6 on 2020-07-06 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_main', '0020_riskmatrix'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskmatrix',
            name='user',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
