# Generated by Django 3.0.6 on 2020-07-23 01:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('smart_main', '0023_auto_20200721_0200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('re_name', models.CharField(max_length=20)),
                ('re_desc', models.TextField(blank=True)),
                ('re_crm', models.TextField(blank=True)),
                ('re_ss', models.TextField(blank=True)),
                ('re_qa', models.TextField(blank=True)),
                ('re_cm', models.TextField(blank=True)),
            ],
        ),
    ]
