# Generated by Django 3.0.6 on 2020-07-31 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_main', '0026_nodegroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nodegroup',
            name='ng_ps',
        ),
        migrations.AlterField(
            model_name='hazardinstance',
            name='hi_inli',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='hazardinstance',
            name='hi_inrr',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='hazardinstance',
            name='hi_inse',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='hazardinstance',
            name='hi_reli',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='hazardinstance',
            name='hi_rerr',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='hazardinstance',
            name='hi_rese',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
