# Generated by Django 3.0.6 on 2020-08-01 04:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('smart_main', '0028_auto_20200801_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodegroup',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
