# Generated by Django 3.0.6 on 2020-08-01 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_main', '0029_auto_20200801_0449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodegroup',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
