# Generated by Django 3.1 on 2020-08-13 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_main', '0033_cause_causecontrol_effect_effectcontrol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cause',
            name='ca_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='causecontrol',
            name='caco_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='effect',
            name='ef_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='effectcontrol',
            name='efco_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='re_name',
            field=models.CharField(max_length=100),
        ),
    ]
