# Generated by Django 3.1 on 2020-08-17 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_main', '0036_auto_20200814_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodegroup',
            name='label',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
